apiVersion: v1
kind: Service
metadata:
  name: guestbook-app
  labels:
    name: guestbook-app-service
    app: guestbook-app

spec:
  type: LoadBalancer
  ports:
    - port : 80
  selector:
      name: guestbook-app-pod
      app: guestbook-app
