apiVersion: apps/v1
kind: Deployment
metadata:
  name: guestbook-app-deployment
  labels:
    app: guestbook-app

spec:
  template:
    metadata:
      name: guestbook-app-pod
      labels:
        name: guestbook-app-pod
        app: guestbook-app

    spec:
      containers:
      - image: kubernetes/guestbook:v2
        name: guestbook-app

  replicas: 3
  selector:
    matchLabels:
      name: guestbook-app-pod
      app: guestbook-app
