apiVersion: apps/v1
kind: Deployment
metadata:
  name: worker-app-deployment
  labels:
    app: voting-app

spec:
  template:
    metadata:
      name: worker-app-pod
      labels:
        name: worker-app-pod
        app: voting-app
    spec:
      containers:
        - name: worker-app
          image: dockersamples/examplevotingapp_worker

  replicas: 3

  selector:
    matchLabels:
      name: worker-app-pod
